# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d608e0965b94046355c6fb9f28cdb885c7934aafa506319db7da7565aa186d5d95c7fd015a994d8ef77de01534400a81e17dcd19faafee755a2409c5171225cf

test:
  secret_key_base: a881f667b649cb2883871435664eb76d9a6efc7be8106c12c5132cbadb3c76e5d8bba18bc0d96d3d99787a683bb78b7aa8bf7dece22028a57dd4fc7d932178bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 18836eadf1cb97c27becd3ac624a6844e8cf70212004ec5637206d8ed2d8216ab8ca350b34b03e627e31d54d7acfe5ae8535bcad188a6d91cf2520c321cd982b
